# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7c4c8ebc3853086273953884657e54eb16c19cdbbcc41de82776a9e5ba4c7eaf0cfffe645ddf0c2e02fb0352653285b02b0aab101fed1e0faf1d05c13e81e45

test:
  secret_key_base: 5a82a5c0db6af8fcc18e758dbfbcb726edc69679ca1d759892873d798bc5bb8b3fd0238e02b25c632d806e02ec7c9b8fbaf0b3f3af249b6d5ddecd53ce6b08f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
